// scripts/brand/build-brand.mjs
// Builds every brand asset from one source: Fraunces 600 at optical size 144 (the face of the
// official logo, see scripts/brand/fraunces-instance.py) and the geometry of the official small
// mark, the admin home screen icon (public/admin-icon-512.png). Run from the repo root:
//   node scripts/brand/build-brand.mjs
// Writes, and every output is committed:
//   lib/brand/logoPaths.js       the logo and the small mark as vector paths (the web, the PDF)
//   public/brand/*               the logo as SVG and the email PNG
//   public/icons/*, favicon.ico  the app icons and the favicon: the small mark, realtor palette
//   public/splash/*              the iOS launch images (lib/brand/splash.js)
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createRequire } from 'node:module';
import { SPLASH, splashFile } from '../../lib/brand/splash.js';

const require = createRequire(import.meta.url);
const opentype = require('opentype.js');
const { Resvg } = require('@resvg/resvg-js');

// The tokens (components/theme.js), as literals so this script runs without the React tree.
const INK = '#0f0f10', RED = '#d72027', PAPER = '#faf8f3', INST = '#101012', INST_TEXT = '#e8e4d9', WHITE = '#ffffff';
// The small mark in two palettes on one geometry. The admin install (public/admin-icon-*.png, never
// rebuilt here) is the ink ground with the red stripe and the paper R. The realtor app is its
// inverse: the red ground, the ink stripe (inst, #101012) and the white R (card, #ffffff).
export const PALETTES = Object.freeze({
  admin: Object.freeze({ ground: INST, stripe: RED, letter: INST_TEXT }),
  realtor: Object.freeze({ ground: RED, stripe: INST, letter: WHITE }),
});

const tmp = mkdtempSync(join(tmpdir(), 'rl-brand-'));
const ttf = join(tmp, 'fraunces-600-opsz144.ttf');
execFileSync('python3', ['scripts/brand/fraunces-instance.py', ttf], { stdio: 'inherit' });
const font = opentype.loadSync(ttf);
const CAP = font.tables.os2.sCapHeight; // 1400 of 2000
const r2 = (n) => Math.round(n * 100) / 100;

// ── THE LOGO: the red bar, then "Rentletter". Units: the cap height is 100. The proportions are
// the logo the film ends on (components/film/ProductFilm.js): the bar as tall as the capitals,
// centred on them, a sixth of its height wide, then a gap of 0.37 cap, the word tracked -0.025em.
const FS = 100 * font.unitsPerEm / CAP;
const BAR = { w: 17, h: 102, rx: 3.4 };
const GAP = 37;
const probe = font.getPath('Rentletter', 0, 0, FS, { kerning: true, letterSpacing: -0.025 }).getBoundingBox();
const textX = BAR.w + GAP - probe.x1; // the R's left edge sits GAP after the bar
const top = Math.min(probe.y1, -100 - 1); // the ascenders of l and t reach above the capitals
const baseline = -top;
const textPath = font.getPath('Rentletter', textX, baseline, FS, { kerning: true, letterSpacing: -0.025 });
const tb = textPath.getBoundingBox();
const LOGO = {
  w: r2(tb.x2), h: r2(Math.max(tb.y2, baseline + 1)),
  capTop: r2(baseline - 100), baseline: r2(baseline),
  bar: { x: 0, y: r2(baseline - 100 - 1), w: BAR.w, h: BAR.h, rx: BAR.rx },
  text: textPath.toPathData(1),
};
// The bar as a path too (rounded corners as quarter curves), for the PDF, where there is no rx.
{ const { x, y, w, h, rx } = LOGO.bar; const k = r2(rx * 0.4477); // 1 minus the circle constant
  LOGO.barPath = `M${x + rx} ${y}H${x + w - rx}C${x + w - k} ${y} ${x + w} ${r2(y + k)} ${x + w} ${r2(y + rx)}V${r2(y + h - rx)}C${x + w} ${r2(y + h - k)} ${x + w - k} ${r2(y + h)} ${x + w - rx} ${r2(y + h)}H${x + rx}C${k} ${r2(y + h)} ${x} ${r2(y + h - k)} ${x} ${r2(y + h - rx)}V${r2(y + rx)}C${x} ${r2(y + k)} ${k} ${y} ${x + rx} ${y}Z`; }

// ── THE SMALL MARK: the admin icon, measured (public/admin-icon-512.png and -maskable.png): an
// ink square, the red bar, the serif R in the paper text colour. Units: the 512 icon.
const rGlyph = font.charToGlyph('R');
const rBox = rGlyph.getPath(0, 0, 1000).getBoundingBox();
const markR = (x0, bottom, height) => { const s = height / (rBox.y2 - rBox.y1); return rGlyph.getPath(x0 - rBox.x1 * s, bottom - rBox.y2 * s, 1000 * s).toPathData(1); };
const MARK = {
  size: 512,
  any: { bar: { x: 118, y: 132, w: 26, h: 248, rx: 5 }, r: markR(214, 372, 210) },
  maskable: { bar: { x: 174, y: 166, w: 20, h: 180, rx: 4 }, r: markR(249, 338, 155) },
};

mkdirSync('lib/brand', { recursive: true });
writeFileSync('lib/brand/logoPaths.js', `// lib/brand/logoPaths.js  GENERATED by scripts/brand/build-brand.mjs from Fraunces 600, optical
// size 144. Do not edit by hand: change the script and run it again.
// LOGO: the red bar and "Rentletter", in units where the cap height is 100.
// MARK: the small mark (the admin home screen icon), in a 512 square.
export const LOGO = ${JSON.stringify(LOGO)};
export const MARK = ${JSON.stringify(MARK)};
`);

// ── SVG, then PNG ──
const logoSvg = ({ height, ink = INK, bg = null, pad = 0, w = null, h = null }) => {
  const s = height / LOGO.h; const W = w ?? Math.ceil(LOGO.w * s + pad * 2); const H = h ?? Math.ceil(height + pad * 2);
  const ox = (W - LOGO.w * s) / 2, oy = (H - LOGO.h * s) / 2;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">${bg ? `<rect width="${W}" height="${H}" fill="${bg}"/>` : ''}<g transform="translate(${r2(ox)} ${r2(oy)}) scale(${s})"><rect x="${LOGO.bar.x}" y="${LOGO.bar.y}" width="${LOGO.bar.w}" height="${LOGO.bar.h}" rx="${LOGO.bar.rx}" fill="${RED}"/><path d="${LOGO.text}" fill="${ink}"/></g></svg>`;
};
// The mark at a pixel size. At 32 and under the bar snaps to whole pixels, so it stays one crisp
// stroke; the geometry is otherwise the same mark.
const markSvg = ({ px, kind = 'any', palette = PALETTES.realtor }) => {
  const m = MARK[kind]; const s = px / MARK.size; let { x, y, w, h, rx } = m.bar; const { ground, stripe, letter } = palette;
  if (px <= 32) { const X = Math.round(x * s), W = Math.max(1, Math.round(w * s)), Y = Math.round(y * s), H = Math.round(h * s); return `<svg xmlns="http://www.w3.org/2000/svg" width="${px}" height="${px}" viewBox="0 0 ${px} ${px}"><rect width="${px}" height="${px}" fill="${ground}"/><rect x="${X}" y="${Y}" width="${W}" height="${H}" fill="${stripe}"/><g transform="scale(${s})"><path d="${m.r}" fill="${letter}"/></g></svg>`; }
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${px}" height="${px}" viewBox="0 0 ${MARK.size} ${MARK.size}"><rect width="${MARK.size}" height="${MARK.size}" fill="${ground}"/><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="${stripe}"/><path d="${m.r}" fill="${letter}"/></svg>`;
};
const png = (svg) => new Resvg(svg, { font: { loadSystemFonts: false } }).render().asPng();

mkdirSync('public/brand', { recursive: true });
writeFileSync('public/brand/rentletter-logo.svg', logoSvg({ height: 40, pad: 1 }));
// The email logo: 132 wide in the email, drawn at four times for sharp phones, with 4 pixels of
// air round the drawing, transparent so it sits on paper or on white.
const EMAIL_W = 132, EMAIL_X = 4;
const eW = EMAIL_W * EMAIL_X, eH = Math.ceil(((eW - 8) * LOGO.h / LOGO.w + 8) / EMAIL_X) * EMAIL_X; // a whole display pixel tall
writeFileSync('public/brand/rentletter-logo-email.png', png(logoSvg({ height: (eW - 8) * LOGO.h / LOGO.w, w: eW, h: eH })));
writeFileSync('lib/brand/emailLogoSize.js', `// lib/brand/emailLogoSize.js  GENERATED by scripts/brand/build-brand.mjs: the email logo's display size.\nexport const EMAIL_LOGO = { width: ${EMAIL_W}, height: ${Math.round(eH / EMAIL_X)}, path: '/brand/rentletter-logo-email.png' };\n`);

mkdirSync('public/icons', { recursive: true });
const icons = [['icon-192.png', 192, 'any'], ['icon-512.png', 512, 'any'], ['icon-maskable-192.png', 192, 'maskable'], ['icon-maskable-512.png', 512, 'maskable'], ['apple-touch-icon.png', 180, 'any'], ['favicon-32.png', 32, 'any'], ['favicon-16.png', 16, 'any']];
const bytes = {};
for (const [name, px, kind] of icons) { bytes[name] = png(markSvg({ px, kind })); writeFileSync(`public/icons/${name}`, bytes[name]); }
writeFileSync('public/icons/mark.svg', markSvg({ px: 512 }));
// favicon.ico: the 16 and the 32, as PNG entries (every current browser reads them).
const entries = [[16, bytes['favicon-16.png']], [32, bytes['favicon-32.png']]];
const head = Buffer.alloc(6 + 16 * entries.length); head.writeUInt16LE(0, 0); head.writeUInt16LE(1, 2); head.writeUInt16LE(entries.length, 4);
let offset = head.length;
entries.forEach(([px, data], i) => { const o = 6 + 16 * i; head.writeUInt8(px, o); head.writeUInt8(px, o + 1); head.writeUInt8(0, o + 2); head.writeUInt8(0, o + 3); head.writeUInt16LE(1, o + 4); head.writeUInt16LE(32, o + 6); head.writeUInt32LE(data.length, o + 8); head.writeUInt32LE(offset, o + 12); offset += data.length; });
writeFileSync('public/favicon.ico', Buffer.concat([head, ...entries.map(([, d]) => d)]));

// The launch images: paper, the full logo centred at half the screen's width.
mkdirSync('public/splash', { recursive: true });
for (const s of SPLASH) {
  const W = s.w * s.dpr, H = s.h * s.dpr; const lw = W * 0.5; const lh = lw * LOGO.h / LOGO.w;
  writeFileSync(`public${splashFile(s)}`, png(logoSvg({ height: lh, bg: PAPER, w: W, h: H })));
}
// The offline page the service worker (public/sw.js) shows when a page cannot load: paper, the
// logo, one sentence. It reloads by itself when the connection comes back. No script but that.
const offlineLogo = logoSvg({ height: 30, pad: 1 }).replace('<svg ', '<svg role="img" aria-label="Rentletter" ');
writeFileSync('public/offline.html', `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Offline · Rentletter</title><meta name="theme-color" content="${PAPER}"><link rel="icon" href="/favicon.ico">
<style>
@font-face { font-family: 'Inter'; font-weight: 100 900; font-display: swap; src: url('/fonts/inter-latin.woff2') format('woff2'); }
html, body { margin: 0; height: 100%; background: ${PAPER}; color: ${INK}; font-family: 'Inter', -apple-system, sans-serif; }
main { min-height: 100%; box-sizing: border-box; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 24px; padding: max(24px, env(safe-area-inset-top)) 24px max(24px, env(safe-area-inset-bottom)); text-align: center; }
p { margin: 0; font-size: 16px; line-height: 1.5; max-width: 22em; text-wrap: balance; }
</style></head>
<body><main>${offlineLogo}<p>You're offline. Rentletter will reconnect on its&nbsp;own.</p></main>
<script>window.addEventListener('online', function () { location.reload(); });</script>
</body></html>
`);
console.log(`logo ${LOGO.w} by ${LOGO.h} (cap 100), mark, ${icons.length} icons, favicon.ico, ${SPLASH.length} launch images, offline page`);
