// lib/brand/emailLogoSize.js  GENERATED by scripts/brand/build-brand.mjs: the email logo's display size.
export const EMAIL_LOGO = { width: 132, height: 26, path: '/brand/rentletter-logo-email.png' };
